ARG BASE
FROM ${BASE}

RUN apt install -y \
    libglib2.0-dev \
    libxml2-dev \
    automake \
    intltool \
    gtk-doc-tools \
    libtool \
    gettext \
    meson

ARG ARAVIS_VER=0.8.31
ADD https://github.com/AravisProject/aravis/archive/${ARAVIS_VER}.tar.gz /aravis/
RUN tar -C /aravis -xf /aravis/${ARAVIS_VER}.tar.gz
WORKDIR /aravis/aravis-${ARAVIS_VER}
RUN meson setup build && cd build && meson install
